name: CI to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
#     services:
#       db:
#         image: mongo:latest
#         ports: 
#           - "27017:27017"
#       mongo-express:
#         image: mongo-express
# #         depends_on: db
#         ports:
#           - "8081:8081"
#     steps:
#       - name: running mongo-express
# #         run: "http://localhost:8081"
    
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push application
        id: docker_build_application
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          # tags: it is resposible to creating new docker repository with name as below given format          
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flask_gunicorn_img:latest

#       - name: Build and push nginx
#         id: docker_build_nginx
#         uses: docker/build-push-action@v2
#         with:
#           context: ./
#           file: ./nginx/Dockerfile
#           push: true
#           # tags: it is resposible to creating new docker repository with name as below given format          
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginx_img:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_application.outputs.digest }}
